name: Test SSH Connection

on:
  workflow_dispatch: # Позволяет запускать вручную
  push:
    branches: [ main, master ]

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test SSH Connection
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        timeout: 60s
        script: |
          echo "🔍 Testing SSH connection..."
          echo "User: $(whoami)"
          echo "Directory: $(pwd)"
          echo "Date: $(date)"
          echo "✅ SSH connection successful!"
          
    - name: Test Project Directory
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT || 22 }}
        timeout: 60s
        script: |
          echo "🔍 Testing project directory..."
          cd /root/auto-parsers || {
            echo "❌ Directory not found"
            exit 1
          }
          echo "📁 Project directory: $(pwd)"
          echo "📋 Contents:"
          ls -la
          echo "✅ Project directory accessible!"
